/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { HttpValidationError } from './models/http-validation-error';
export { RoomDto } from './models/room-dto';
export { ValidationError } from './models/validation-error';
