/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { loginLoginGet } from '../fn/login/login-login-get';
import { LoginLoginGet$Params } from '../fn/login/login-login-get';

@Injectable({ providedIn: 'root' })
export class LoginService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `loginLoginGet()` */
  static readonly LoginLoginGetPath = '/login';

  /**
   * Login.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `loginLoginGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  loginLoginGet$Response(params: LoginLoginGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return loginLoginGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Login.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `loginLoginGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  loginLoginGet(params: LoginLoginGet$Params, context?: HttpContext): Observable<any> {
    return this.loginLoginGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
