/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createRoomRoomsCreateGet } from '../fn/rooms/create-room-rooms-create-get';
import { CreateRoomRoomsCreateGet$Params } from '../fn/rooms/create-room-rooms-create-get';
import { getAllRoomsRoomsGet } from '../fn/rooms/get-all-rooms-rooms-get';
import { GetAllRoomsRoomsGet$Params } from '../fn/rooms/get-all-rooms-rooms-get';
import { RoomDto } from '../models/room-dto';

@Injectable({ providedIn: 'root' })
export class RoomsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createRoomRoomsCreateGet()` */
  static readonly CreateRoomRoomsCreateGetPath = '/rooms/create';

  /**
   * Create Room.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRoomRoomsCreateGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  createRoomRoomsCreateGet$Response(params: CreateRoomRoomsCreateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomDto>> {
    return createRoomRoomsCreateGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Create Room.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRoomRoomsCreateGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createRoomRoomsCreateGet(params: CreateRoomRoomsCreateGet$Params, context?: HttpContext): Observable<RoomDto> {
    return this.createRoomRoomsCreateGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoomDto>): RoomDto => r.body)
    );
  }

  /** Path part for operation `getAllRoomsRoomsGet()` */
  static readonly GetAllRoomsRoomsGetPath = '/rooms';

  /**
   * Get All Rooms.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRoomsRoomsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoomsRoomsGet$Response(params?: GetAllRoomsRoomsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoomDto>>> {
    return getAllRoomsRoomsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get All Rooms.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRoomsRoomsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoomsRoomsGet(params?: GetAllRoomsRoomsGet$Params, context?: HttpContext): Observable<Array<RoomDto>> {
    return this.getAllRoomsRoomsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoomDto>>): Array<RoomDto> => r.body)
    );
  }

}
